<?php
declare(strict_types=1);

/**
 * Private configuration (database credentials + app key).
 *
 * Stored OUTSIDE the web root when possible, so a GitHub redeploy can never
 * overwrite or expose it. Lookup order:
 *   1. MERIDIAN_DATA_DIR environment variable
 *   2. ../meridian-data  (next to public_html — recommended, automatic on Hostinger)
 *   3. ./storage/private (fallback, blocked from the web by .htaccess)
 */
final class Config
{
    private static ?array $config = null;
    private static bool $loaded = false;

    /** @return string[] */
    public static function candidates(): array
    {
        $dirs = [];
        $env  = getenv("MERIDIAN_DATA_DIR");
        if ($env) {
            $dirs[] = rtrim($env, "/\\");
        }
        $dirs[] = dirname(APP_ROOT) . "/meridian-data";
        $dirs[] = APP_ROOT . "/storage/private";
        return $dirs;
    }

    public static function dataDir(): ?string
    {
        foreach (self::candidates() as $dir) {
            if (@is_file($dir . "/config.php")) {
                return $dir;
            }
        }
        return null;
    }

    /** First location we can write the config to (creates it if needed). */
    public static function writableDir(): ?string
    {
        foreach (self::candidates() as $dir) {
            if (@is_dir($dir)) {
                if (is_writable($dir)) {
                    return $dir;
                }
                continue;
            }
            $parent = dirname($dir);
            if (@is_dir($parent) && is_writable($parent) && @mkdir($dir, 0700, true)) {
                self::protect($dir);
                return $dir;
            }
        }
        return null;
    }

    public static function isOutsideWebroot(string $dir): bool
    {
        $root = realpath(APP_ROOT) ?: APP_ROOT;
        $real = realpath($dir) ?: $dir;
        return !str_starts_with($real, $root);
    }

    public static function load(): ?array
    {
        if (self::$loaded) {
            return self::$config;
        }
        self::$loaded = true;
        $dir = self::dataDir();
        if ($dir) {
            $cfg = require $dir . "/config.php";
            self::$config = is_array($cfg) ? $cfg : null;
        }
        return self::$config;
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        return self::load()[$key] ?? $default;
    }

    /** Use a config in memory (setup wizard) before it is written to disk. */
    public static function setRuntime(array $config): void
    {
        self::$config = $config;
        self::$loaded = true;
    }

    public static function installed(): bool
    {
        return self::load() !== null;
    }

    public static function write(array $config, string $dir): void
    {
        self::protect($dir);
        $php  = "<?php\n// Meridian HR private configuration. Generated by the setup wizard on " . date("c") . ".\n";
        $php .= "// Keep this file private. Never commit it to GitHub.\n";
        $php .= "return " . var_export($config, true) . ";\n";
        $file = $dir . "/config.php";
        $tmp  = $file . "." . bin2hex(random_bytes(4)) . ".tmp";
        if (file_put_contents($tmp, $php, LOCK_EX) === false || !rename($tmp, $file)) {
            @unlink($tmp);
            throw new RuntimeException("Could not write the configuration file.");
        }
        @chmod($file, 0600);
        self::$config = $config;
        self::$loaded = true;
    }

    private static function protect(string $dir): void
    {
        $ht = $dir . "/.htaccess";
        if (!is_file($ht)) {
            @file_put_contents($ht, "Require all denied\nDeny from all\n");
        }
        if (!is_file($dir . "/index.html")) {
            @file_put_contents($dir . "/index.html", "");
        }
    }
}
